---
# tasks file for ansible_galaxy_role_ubuntu-docker

- name: "Docker | Install packages"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: "Docker | Check GPG key file"
  become: yes
  ignore_errors: yes
  shell: ls {{ docker.gpg.key.dist.path }} >/dev/null
  register: ls_gpg_key_result

- name: "Docker | Debug GPG key ls result"
  become: yes
  debug:
    msg: "{{ ls_gpg_key_result.rc }}"

- block:

  - name: "Docker | Download GPG key"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    shell:
      cmd: curl -fsSL {{ docker.gpg.key.url }} | gpg --dearmor -o {{ docker.gpg.key.dist.path }}

  - name: "Docker | Add sources list"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    shell:
      cmd: |
        echo \
          "deb [arch=amd64 signed-by={{ docker.gpg.key.dist.path }}] {{ docker.deb.url }} \
          $(lsb_release -cs) stable" | tee {{ docker.deb.sources.list.path }} > /dev/null

  when: ls_gpg_key_result.rc != 0

- name: "Docker | Install Docker Engine"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: "Docker | Create Group"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  group:
    name: docker
    state: present

- name: "Docker | Add User to Docker Group"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  user:
    name: "{{ ansible_user }}"
    append: yes
    group: docker
